In [5]:
import model_loader
import pipeline
from PIL import Image
from pathlib import Path
from transformers import CLIPTokenizer
import torch

DEVICE = "cpu"

ALLOW_CUDA = False
ALLOW_MPS = False

if torch.cuda.is_available() and ALLOW_CUDA:
    DEVICE = "cuda"
elif (torch.has_mps or torch.backends.mps.is_available() or torch.backends.mps.is_built()) and ALLOW_MPS:
    DEVICE = "mps"
print(f"Using device: {DEVICE}")



tokenizer = CLIPTokenizer("../data/vocab.json", merges_file="../data/merges.txt")
model_file = "../data/v1-5-pruned-emaonly.ckpt"
models = model_loader.preload_models_from_standard_weights(model_file, DEVICE)

## TEXT TO IMAGE

# prompt = "A dog with sunglasses, wearing comfy hat, looking at camera, highly detailed, ultra sharp, cinematic, 100mm lens, 8k resolution."
# prompt = "A dog stretching on the floor, highly detailed, ultra sharp, cinematic, 100mm lens, 8k resolution."
# prompt = "A camel in the desert wearing sunglasses highly detailed, ultra sharp, cinematic, 100mm lens, 8k resolution."
prompt = "" # did it not work, or is the image useless?
uncond_prompt = ""  # Also known as negative prompt
do_cfg = True
cfg_scale = 8  # min: 1, max: 14

## IMAGE TO IMAGE

input_image = None
# Comment to disable image to image
image_path = "../images/signal.jpg" # must be a jpeg
input_image = Image.open(image_path)
# Higher values means more noise will be added to the input image, so the result will further from the input image.
# Lower values means less noise is added to the input image, so output will be closer to the input image.
strength = 0.1

## SAMPLER

sampler = "ddpm"
num_inference_steps = 50
seed = 42

output_image = pipeline.generate(
    prompt=prompt,
    uncond_prompt=uncond_prompt,
    input_image=input_image,
    strength=strength,
    do_cfg=do_cfg,
    cfg_scale=cfg_scale,
    sampler_name=sampler,
    n_inference_steps=num_inference_steps,
    seed=seed,
    models=models,
    device=DEVICE,
    idle_device="cpu",
    tokenizer=tokenizer,
)

# print(f"z's shape: {output_image.shape},\nz: {output_image}")


# Combine the input image and the output image into a single image.
# Image.fromarray(output_image)

Current Path: /Users/amahmed/Desktop/UMass/Thesis/models/pytorch-stable-diffusion/sd
Using device: cpu


/var/folders/cm/6lf2qlhd437d56z2j9mprb480000gn/T/ipykernel_94255/2145690705.py:23: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  elif (torch.has_mps or torch.backends.mps.is_available() or torch.backends.mps.is_built()) and ALLOW_MPS:


FileNotFoundError: [Errno 2] No such file or directory: '../pytorch-stable-diffusion/data/vocab.json'

In [2]:
print(f"z's shape: {output_image.shape},\nz: {output_image}")




z's shape: (128, 128, 3),
z: [[[247 245 247]
  [247 246 246]
  [247 246 252]
  ...
  [247 254 251]
  [243 251 254]
  [243 255 249]]

 [[248 245 252]
  [246 248 250]
  [248 249 249]
  ...
  [244 255 251]
  [246 251 250]
  [245 255 254]]

 [[247 243 251]
  [246 248 251]
  [247 248 247]
  ...
  [246 254 252]
  [247 252 252]
  [246 254 255]]

 ...

 [[252 250 251]
  [251 251 253]
  [253 251 249]
  ...
  [253 254 248]
  [255 251 247]
  [251 255 248]]

 [[248 255 255]
  [251 248 251]
  [254 249 250]
  ...
  [253 252 248]
  [253 252 246]
  [251 254 249]]

 [[251 250 246]
  [255 253 255]
  [252 254 252]
  ...
  [252 255 254]
  [253 255 253]
  [251 255 241]]]
